# @package _global_

defaults:
  - _base

model:
  scorer:
    target:
      _target_: src.model.module.scorer.sdp_scorer.CPD_SecondOrderSDPScorer
    rank: 300
    n_mlp_rel: 300
    n_mlp_sib: 300
    scaling: False


  loss:
    target:
      _target_: src.loss.sdp_loss.CPD_MFLoss
    max_iter: 2
    
  name: 'cpd_sdp_rank_${model.scorer.rank}'








