# @package _global_

defaults:
  - _base

model:
  scorer:
    target:
      _target_: src.model.module.scorer.sdp_scorer.MF_SecondOrderSDPScorer
    rank: 300
    n_mlp_rel: 300
    n_mlp_arc: 600
    n_mlp_sib: 300
    scaling: False

  loss:
    target:
      _target_: src.loss.sdp_loss.MFLoss
    max_iter: 2
    
  name: 'mf_sdp_rank_${model.scorer.rank}'








