# @package _global_
defaults:
  - _base

datamodule:
  target:
    _target_: src.datamodule.dp_data.DepData
  name: 'ctb'
  train_dep: "${root}/data/ctb/train.ctb.conll"
  dev_dep: "${root}/data/ctb/dev.ctb.conll"
  test_dep: "${root}/data/ctb/test.ctb.conll"
  cache: "${root}/data/ctb/ctb.dep.pickle"
  cache_bert: "${root}/data/ctb/ctb.dep.cache_${datamodule.bert}"
  ext_emb_path: "${root}/data/glove.6B.100d.txt"
  ignore_punct: True
  clean_word: True
  bert: 'bert-base-chinese'
  use_pos: True
  force_projectivity: True

model:
  metric:
    target:
      _target_: src.model.metric.AttachmentMetric
    write_result_to_file: True


